-- ==========================================
-- HYBRID COMMUNITY FEATURE - DATABASE SCHEMA
-- ==========================================
-- Execute this SQL in Supabase SQL Editor
-- This creates: teams, community_posts tables + RLS policies

-- 1. Create Teams Table (Untuk menampung data Kantor)
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  join_code text unique not null, -- Kode unik (misal: "DGTNZ-88")
  created_by bigint references public.users(id) on delete set null, -- Changed from UUID to BIGINT to match local users table
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Update Users Table (Agar user punya 'KTP' kantor)
-- Add team_id column if not exists
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'users' 
    AND column_name = 'team_id'
  ) THEN
    ALTER TABLE public.users ADD COLUMN team_id bigint references public.teams(id) on delete set null;
  END IF;
END $$;

-- 3. Create Community Posts Table (Satu tabel untuk semua)
create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  content text not null, -- Isi postingan
  scope text check (scope in ('INTERNAL', 'GLOBAL')) not null default 'GLOBAL', -- Pembeda Jalur
  team_id bigint references public.teams(id) on delete cascade, -- Wajib diisi kalau scope INTERNAL
  user_id text not null, -- Changed from UUID to TEXT to store Supabase Auth UUID as string (no FK constraint)
  author_name text not null, -- Nama penulis (biar gak join table terus)
  author_role text, -- Opsional (misal: "Staff GA")
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. AKTIFKAN KEAMANAN (RLS - Row Level Security)
-- Ini fitur KUNCI Supabase. Logic kodingan aman ada di sini.

alter table public.teams enable row level security;
alter table public.community_posts enable row level security;

-- Drop existing policies if any
drop policy if exists "Enable read access for all users" on public.teams;
drop policy if exists "Enable insert for authenticated users only" on public.teams;
drop policy if exists "Hybrid Visibility Policy" on public.community_posts;
drop policy if exists "Enable insert for authenticated users only" on public.community_posts;
drop policy if exists "Enable update own posts" on public.community_posts;
drop policy if exists "Enable delete own posts" on public.community_posts;

-- Policy untuk Teams: Semua orang boleh baca (untuk validasi kode), join/buat perlu auth
create policy "Enable read access for all users" 
  on public.teams for select 
  using (true);

create policy "Enable insert for authenticated users only" 
  on public.teams for insert 
  with check (
    auth.role() = 'authenticated' OR auth.role() = 'service_role'
  );

-- Policy untuk Posts (INI YANG PALING PENTING!)
-- User boleh LIHAT postingan JIKA:
-- 1. Postingan itu GLOBAL (Public)
-- 2. ATAU Postingan itu INTERNAL, TAPI team_id user SAMA dengan team_id postingan.

create policy "Hybrid Visibility Policy"
  on public.community_posts
  for select using (
    (scope = 'GLOBAL') 
    OR 
    (scope = 'INTERNAL' AND team_id in (
      select team_id from public.users where email = (select email from auth.users where id = auth.uid())
    ))
  );

-- User boleh NULIS postingan (selalu boleh asal login)
create policy "Enable insert for authenticated users only" 
  on public.community_posts 
  for insert 
  with check (
    auth.role() = 'authenticated' OR auth.role() = 'service_role'
  );

-- User boleh EDIT postingan sendiri
create policy "Enable update own posts"
  on public.community_posts
  for update using (
    user_id = auth.uid()::text
  );

-- User boleh HAPUS postingan sendiri
create policy "Enable delete own posts"
  on public.community_posts
  for delete using (
    user_id = auth.uid()::text
  );

-- 5. Create indexes for performance
create index if not exists idx_teams_join_code on public.teams(join_code);
create index if not exists idx_users_team_id on public.users(team_id);
create index if not exists idx_posts_scope on public.community_posts(scope);
create index if not exists idx_posts_team_id on public.community_posts(team_id);
create index if not exists idx_posts_user_id on public.community_posts(user_id);
create index if not exists idx_posts_created_at on public.community_posts(created_at desc);

-- Success message
DO $$ 
BEGIN 
  RAISE NOTICE '✅ Community tables created successfully!';
  RAISE NOTICE '✅ RLS policies enabled!';
  RAISE NOTICE '✅ Indexes created for performance!';
END $$;
