-- =====================================================
-- Create Quizzes Table for Quiz.wtf Feature
-- Run this in Supabase SQL Editor
-- =====================================================

-- 1. Create quizzes table
CREATE TABLE IF NOT EXISTS public.quizzes (
    id TEXT PRIMARY KEY,           -- nanoid(7) generated by backend
    topic TEXT NOT NULL,           -- Topic entered by user
    title TEXT NOT NULL,           -- Quiz title generated by AI
    questions JSONB NOT NULL,      -- Array of 20 questions with options and explanations
    user_id INTEGER NOT NULL,      -- INTEGER to match Prisma schema (User.id is Int)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_quizzes_user_id ON public.quizzes(user_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_created_at ON public.quizzes(created_at DESC);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies
-- Allow anyone to read quizzes by ID (for playing)
DROP POLICY IF EXISTS "Anyone can read quiz by ID" ON public.quizzes;
CREATE POLICY "Anyone can read quiz by ID" 
ON public.quizzes 
FOR SELECT 
USING (true);

-- Allow authenticated users to create quizzes
DROP POLICY IF EXISTS "Authenticated users can create quizzes" ON public.quizzes;
CREATE POLICY "Authenticated users can create quizzes" 
ON public.quizzes 
FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

-- Users can view their own quizzes
DROP POLICY IF EXISTS "Users can view own quizzes" ON public.quizzes;
CREATE POLICY "Users can view own quizzes" 
ON public.quizzes 
FOR SELECT 
USING (user_id = (SELECT id FROM users WHERE id::text = auth.uid()::text));

-- 5. Add credits column to users table (if not exists)
-- Note: This assumes you have a users table separate from auth.users
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users') THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'users' AND column_name = 'credits'
        ) THEN
            ALTER TABLE public.users ADD COLUMN credits INTEGER DEFAULT 10;
        END IF;
    END IF;
END $$;

-- 6. Create function to reset credits daily (optional - for future automation)
-- This can be scheduled using pg_cron extension
CREATE OR REPLACE FUNCTION reset_daily_credits()
RETURNS void AS $$
BEGIN
    UPDATE public.users SET credits = 10 WHERE credits < 10;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- VERIFICATION QUERIES
-- Run these after creating the table to verify
-- =====================================================

-- Check if table exists
-- SELECT * FROM information_schema.tables WHERE table_name = 'quizzes';

-- Check table structure
-- SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'quizzes';

-- Check RLS policies
-- SELECT * FROM pg_policies WHERE tablename = 'quizzes';
